// kitchenware.js - real data recovered from git history; edit prices/details as needed.
var kitchenware = [
    { name: "Moringa/Soursop/Ashwagandha", price: "250 KSh each", details: "Health supplements – boost immunity, fight anxiety, reduce inflammation", image: "images/kitchenware/moringa-soursoups.jpg" },
    { name: "3-in-1 Sugar/Tea/Coffee Glass Bottle", price: "2,200 KSh", details: "Available at the shop", image: "images/kitchenware/sugartea-glassbottle.jpg" },
    { name: "6-Set Plate", price: "2,200 KSh", details: "Available at the shop", image: "images/kitchenware/6set-plate.jpg" },
    { name: "Egg Tray (Holds 32 Eggs)", price: "1,600 KSh", details: "Plastic, 36 pcs available", image: "images/kitchenware/egg-tray.jpg" },
    { name: "Ramtons Corded Kettle 1.7L", price: "1,800 KSh", details: "Quality kettle", image: "images/kitchenware/ramtons-kettle.jpg" },
    { name: "Cream White and Gold Holder", price: "1,300 KSh each / 4,800 KSh (set of 5)", details: "Available at the shop", image: "images/kitchenware/gold-holder.jpg" },
    { name: "Gold and White Ceramic Dinner Set (24pcs)", price: "6,000 KSh", details: "6 plates, 6 side plates, 6 bowls, 6 cups", image: "images/kitchenware/gold-dinnerset.jpg" },
    { name: "27pc Dinner Set", price: "5,700 KSh", details: "Complete dinner set", image: "images/kitchenware/27pcs.jpg" },
    { name: "8pc Milton Pearl Combo", price: "4,800 KSh", details: "3 hotpots, 4 tumblers, 1L flask", image: "images/kitchenware/8pcs-milton.jpg" },
    { name: "13pc Breakfast Set", price: "5,800 KSh", details: "6 plates, 6 mugs, 1 tea urn, 1 flask", image: "images/kitchenware/13pcs-breakfastset.jpg" },
    { name: "7pc Breakfast Set (Marble)", price: "3,900 KSh", details: "Tea urn + mugs", image: "images/kitchenware/7pcs-breakfastset.jpg" },
    { name: "3pc Gold Ceramic Casserole", price: "3,500 KSh", details: "3L, 2L, 1L with glass covers", image: "images/kitchenware/3pcsgold-casserole.jpg" },
    { name: "Nunix A2C-X2 Water Dispenser", price: "13,000 KSh", details: "Black, bottom load, hot/cold, music system", image: "images/kitchenware/black-nunix.jpg" },
    { name: "Eurochef 3Gas+1 Electric Cooker", price: "7,800 KSh", details: "With shelves", image: "images/kitchenware/eurochef-3gas.jpg" },
    { name: "Bosch & Dessini Pressure Cooker", price: "5,800 KSh", details: "6L, 1000W", image: "images/kitchenware/bosch-dessini.jpg" },
    { name: "Cast Iron Sizzling Plate", price: "1,500 KSh", details: "On wooden tray, oval/round", image: "images/kitchenware/castiron-plate.jpg" },
    { name: "Silvercrest 2-in-1 Blender", price: "2,900 KSh", details: "Commercial", image: "images/kitchenware/silver-crest.jpg" },
    { name: "Von Standing Cooker (3G+1E)", price: "33,500 KSh", details: "50x60cm, electric oven, rotisserie", image: "images/kitchenware/von-cooker.jpg" },
    { name: "3-in-1 Water Bottle", price: "1,200 KSh", details: "Multipurpose", image: "images/kitchenware/3in1.jpg" },
    { name: "3-in-1 Bottle (second listing)", price: "1,200 KSh", details: "Assorted colors", image: "images/kitchenware/3in12.jpg" },
    { name: "Heavy Grip Rubber Floor Mat", price: "1,600 KSh", details: "2pcs set, 40x60/40x120cm", image: "images/kitchenware/grip-rubber.jpg" },
    { name: "Plain White Plates (6pcs)", price: "2,000 KSh", details: "10.5\"", image: "images/kitchenware/plain-white.jpg" },
    { name: "Smart Pro Digital Microwave", price: "8,400 KSh", details: "20L, black, defrost", image: "images/kitchenware/smart-pro.jpg" },
    { name: "Black Opal Dinner Plate Set", price: "2,000 KSh", details: "6 dinner plates", image: "images/kitchenware/black-opal.jpg" },
    { name: "7pc Tea Set", price: "6,000 KSh", details: "Elegant", image: "images/kitchenware/7piece-teaset.jpg" },
    { name: "Coffee Mugs (6pcs)", price: "1,100 KSh", details: "Golden touch, 370ml", image: "images/kitchenware/coffee-mugs.jpg" },
    { name: "12pc Glass Dinner Set", price: "2,300 KSh", details: "6 cups, 6 plates", image: "images/kitchenware/12pcs-dinnerset.jpg" },
    { name: "6pc Ceramic Cups", price: "750 KSh", details: "350ml", image: "images/kitchenware/ceramic-cups.jpg" },
    { name: "Green Long Cups (400ml)", price: "1,050 KSh", details: "Set of ?", image: "images/kitchenware/long-cups.jpg" },
    { name: "Unique Ceramic Mugs (6pcs)", price: "950 KSh", details: "400ml", image: "images/kitchenware/unique-mugs.jpg" },
    { name: "Black Ceramic Mugs (6pcs)", price: "750 KSh", details: "350ml", image: "images/kitchenware/blackwhite-cups.jpg" },
    { name: "12pc Glass Dinner Set (2nd)", price: "2,150 KSh", details: "6 cups, 6 plates", image: "images/kitchenware/12pc-set.jpg" },
    { name: "Clear Food Covers (100pc)", price: "300 KSh", details: "Stretch covers", image: "images/kitchenware/food-covers.jpg" },
    { name: "72pc Cookware Set", price: "11,000 KSh", details: "Complete cookware set", image: "images/kitchenware/72pcs-kitchenware.jpg" },
    { name: "6 Space Gold Glass Holder", price: "2,500 KSh", details: "Elegant 6-space gold finish glass holder", image: "images/kitchenware/sixspace-glasshoder.jpg" },
    { name: "Bosch 11pc Cookware", price: "8,600 KSh (Promotion)", details: "Made in Germany", image: "images/kitchenware/bosch-11pcs.jpg" },
    { name: "3-in-1 Chaffing Dish", price: "6,800 KSh", details: "Dark green & gold", image: "images/kitchenware/goldchaffing.jpg" },
    { name: "Ecomax 3+1 Standing Cooker", price: "20,000 KSh", details: "50*55cm, free accessories", image: "images/kitchenware/ecomax-cooker.jpg" },
    { name: "Nunix Water Dispenser (12,500)", price: "12,500 KSh", details: "Black, bottom load", image: "images/kitchenware/nunix-dispenser.jpg" },
    { name: "Donnor Berry 16pcs Cookware Set", price: "16,500 KSh", details: "Granite nonstick", image: "images/kitchenware/donnerberry-cookware.jpg" },
    { name: "Single Gold Fruit Rack", price: "1,200 KSh", details: "Elegant gold fruit rack", image: "images/kitchenware/gold-fruitrack.jpg" },
    { name: "Phisma 9pc Cookware Set", price: "13,000 KSh", details: "Nonstick cookware set", image: "images/kitchenware/phisma-cookware.jpg" },
    { name: "Milton Oyster 8pc Combo", price: "4,600 KSh", details: "3 hotpots, 4 tumblers, 1L flask", image: "images/kitchenware/milton-oyster.jpg" },
    { name: "Telaisi Juicer", price: "6,999 KSh", details: "1000W juicer", image: "images/kitchenware/telaisi-juicer.jpg" },
    { name: "Dessini Electric Pressure Cooker", price: "6,200 KSh", details: "6L electric pressure cooker", image: "images/kitchenware/dessini-cooker.jpg" },
    { name: "Double Juice Dispenser", price: "12,000 KSh", details: "Commercial juice dispenser", image: "images/kitchenware/juice-dispenser.jpg" },
    { name: "Redberry Stello Hotpot Set", price: "6,500 KSh", details: "Premium stainless steel hotpot", image: "images/kitchenware/redberry-stello.jpg" },
    { name: "Pearl Platina Hotpot Set (4pc)", price: "4,800 KSh", details: "0.7L,1.0L,1.7L,2.5L", image: "images/kitchenware/pearl-platina.jpg" },
    { name: "Copper Deep Frying Pan", price: "3,000 KSh", details: "Copper pan", image: "images/kitchenware/cooper-pan.jpg" },
    { name: "Nunix A1C Water Dispenser (10,400)", price: "10,400 KSh", details: "Black/silver, hot & cold", image: "images/kitchenware/nunix-a1c.jpg" },
    { name: "8pc Aluminium Steel Cookware", price: "4,200 KSh", details: "No lids", image: "images/kitchenware/8pcs-alluminium.jpg" },
    { name: "7pcs Enamel Cast Iron Pots", price: "9,200 KSh", details: "Milk pot, soup pot, casserole, frying pan", image: "images/kitchenware/7pcs-enamel.jpg" },
    { name: "11pcs Raw Cast Iron Cookware", price: "17,500 KSh", details: "Black, good quality", image: "images/kitchenware/11pcs-ironcast.jpg" },
    { name: "Meat Butchery Cuts", price: "1,000 KSh", details: "meat and butchery cuts", image: "images/kitchenware/meat-box.jpg" },
    { name: "Borosilicate Glass Cookware", price: "2,500 KSh (2.5L)", details: "Wooden handle, heavy", image: "images/kitchenware/glass-cookware.jpg" },
    { name: "Japanese Dinner Set", price: "3,500 KSh", details: "6 dinner plates, 6 side plates, 6 bowls, 6 cups", image: "images/kitchenware/japanese-set.jpg" },
    // ---- Photos with no recovered price/details: please edit these ----
    { name: "24Pcs Dinnerset", price: "Call for Price", details: "", image: "images/kitchenware/24pcs-dinnerset.jpg" },
    { name: "Airtight Jars", price: "Call for Price", details: "", image: "images/kitchenware/airtight-jars.jpg" },
    { name: "Airtight2 Jars", price: "Call for Price", details: "", image: "images/kitchenware/airtight2-jars.jpg" },
    { name: "Ceramic Jars", price: "Call for Price", details: "", image: "images/kitchenware/ceramic-jars.jpg" },
    { name: "Eurochef", price: "Call for Price", details: "", image: "images/kitchenware/eurochef.jpg" },
    { name: "Glass Coffeetable", price: "Call for Price", details: "", image: "images/kitchenware/glass-coffeetable.jpg" },
    { name: "Glass Dispenser", price: "Call for Price", details: "", image: "images/kitchenware/glass-dispenser.jpg" },
    { name: "Hotpots", price: "Call for Price", details: "", image: "images/kitchenware/hotpots.jpg" },
    { name: "Japanese Mugs", price: "Call for Price", details: "", image: "images/kitchenware/japanese-mugs.jpg" },
    { name: "Pitcher", price: "Call for Price", details: "", image: "images/kitchenware/pitcher.jpg" },
    { name: "Ramtons 2Burner", price: "Call for Price", details: "", image: "images/kitchenware/ramtons-2burner.jpg" },
    { name: "Signature Spark", price: "Call for Price", details: "", image: "images/kitchenware/signature-spark.jpg" },
    { name: "Silicone Set", price: "Call for Price", details: "", image: "images/kitchenware/silicone-set.jpg" },
    { name: "Syinix Blender", price: "Call for Price", details: "", image: "images/kitchenware/syinix-blender.jpg" },
    { name: "Ugali Cooker", price: "Call for Price", details: "", image: "images/kitchenware/ugali-cooker.jpg" }
];
